version: "3.9"

volumes:
  acme-challenge:
    driver: local

services:
  nginx-fallback:
    image: nginx:1.23.1-alpine
    container_name: nginx-fallback
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./etc/nginx/templates/fallback.conf.template:/etc/nginx/templates/default.conf.template:ro
      - acme-challenge:/var/www/acme-challenge:ro
    ports:
      - "80:80"

  certbot:
    image: certbot/certbot
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt:rw
      - acme-challenge:/var/www/acme-challenge:rw
