version: "3.9"

volumes:
  certbot:
    driver: local

services:
  nginx:
    image: nginx:1.23.1-alpine
    container_name: nginx
    environment:
      - DOMAIN=${DOMAIN}
    restart: always
    volumes:
      - ${NGINX_CONFIG_FALLBACK_TEMPLATE_FILENAME}:/etc/nginx/templates/default.conf.template:ro
      - certbot:/var/www/certbot:ro
    ports:
      - "80:80"

  certbot:
    image: certbot/certbot
    volumes:
      - ${LETSENCRYPT_PATH}:/etc/letsencrypt:rw
      - certbot:/var/www/certbot:rw
